unitDict={
'Barrier Forge':{'supply':0},
'Cluster Bolt':{'costDict':{'green':-4},
'supply':10},
'Endostructor':{'supply':0},
'Eviscerator':{'supply':0},
'Exostructor':{'supply':0},
'Fire Spinner':{'costDict':{'red':-20},
'supply':1},
'Gunbot':{'supply':0},
'Gunbot Forge':{'supply':0},
'Lunarch HQ':{'supply':0},
'Overwork':{'supply':4},
'Shard':{'supply':0},
'The Gift':{'supply':1},
'Tough Barrier':{'supply':0},
'Tough Gunbot':{'supply':0},
'VelKar':{'supply':0},
'Vile Doombot':{'supply':0},
'Vile Engineer':{'supply':0},
'Vile Gunbot':{'supply':0},
'Vile Mech':{'supply':0},
'Vile Tarsier':{'supply':0},
'Vile Wall':{'supply':0},
'Weak Barrier':{'supply':0},
'Auride Core':{'costDict':{'gold':-1,'blue':-1},
'supply':4},
'Barrier':{'costDict':{'gold':-1,'green':-1},
'supply':20},
'Cryo Ray':{'costDict':{'gold':-1,'green':-1},
'supply':10},
'Ferritin Sac':{'costDict':{'gold':-1,'red':-1},
'supply':10},
'Forcefield':{'costDict':{'gold':-1,'green':-1},
'supply':20},
'Galvani Drone':{'costDict':{'gold':-1,'energy':-1},
'supply':10},
'Gauss Charge':{'costDict':{'gold':-1,'green':-1},
'supply':20},
'Nitrocybe':{'costDict':{'gold':-1,'red':-1},
'supply':20},
'Pixie':{'costDict':{'gold':-1,'blue':-1},
'supply':20},
'Resophore':{'costDict':{'gold':-1,'green':-1,'red':-1},
'supply':1},
'Thermite Core':{'costDict':{'gold':-1,'blue':-1},
'supply':4},
'Venge Cannon':{'costDict':{'gold':-1,'green':-3},
'supply':10},
'Doomed Drone':{'costDict':{'gold':-2,'energy':-1},
'supply':10},
'Engineer':{'costDict':{'gold':-2},
'supply':20},
'Frostbite':{'costDict':{'gold':-2,'red':-1},
'supply':20},
'Husk':{'costDict':{'gold':-2,'red':-1},
'supply':20},
'Nivo Charge':{'costDict':{'gold':-2,'green':-1},
'supply':10},
'Ossified Drone':{'costDict':{'gold':-2,'red':-1},
'supply':1},
'Plexo Cell':{'costDict':{'gold':-2,'green':-2},
'supply':10},
'Trinity Drone':{'costDict':{'gold':-2,'energy':-1,'green':-1},
'supply':10},
'Vivid Drone':{'costDict':{'gold':-2,'energy':-2},
'supply':10},
'Antima Comet':{'costDict':{'gold':-3,'green':-1,'blue':-1,'red':-1},
'supply':1},
'Auric Impulse':{'costDict':{'gold':-3,'energy':-1},
'supply':20},
'Blood Pact':{'costDict':{'gold':-3,'red':-1},
'supply':10},
'Drone':{'costDict':{'gold':-3,'energy':-1},
'supply':20},
'Immolite':{'costDict':{'gold':-3,'red':-1},
'supply':20},
'Manticore':{'costDict':{'gold':-3,'blue':-2},
'supply':4},
'Oxide Mixer':{'costDict':{'gold':-3,'blue':-1},
'supply':4},
'Perforator':{'costDict':{'gold':-3,'red':-1},
'supply':10},
'Scorchilla':{'costDict':{'gold':-3,'green':-1,'red':-1},
'supply':10},
'Chrono Filter':{'costDict':{'gold':-4},
'supply':1},
'Conduit':{'costDict':{'gold':-4},
'supply':10},
'Electrovore':{'costDict':{'gold':-4,'red':-1},
'supply':10},
'Fission Turret':{'costDict':{'gold':-4,'green':-1},
'supply':10},
'Grimbotch':{'costDict':{'gold':-4,'red':-1},
'supply':10},
'Mobile Animus':{'costDict':{'gold':-4},
'supply':10},
'Steelforge':{'costDict':{'gold':-4},
'supply':4},
'Tarsier':{'costDict':{'gold':-4,'red':-1},
'supply':10},
'Blastforge':{'costDict':{'gold':-5},
'supply':10},
'Centrifuge':{'costDict':{'gold':-5},
'supply':1},
'Deadeye Operative':{'costDict':{'gold':-5,'blue':-2},
'supply':4},
'Doomsplitter':{'costDict':{'gold':-5,'blue':-1},
'supply':10},
'Endotherm Kit':{'costDict':{'gold':-5,'green':-3,'red':-1},
'supply':1},
'Feral Warden':{'costDict':{'gold':-5,'green':-1,'red':-1},
'supply':10},
'Flame Animus':{'costDict':{'gold':-5,'blue':-1},
'supply':4},
'Frost Brooder':{'costDict':{'gold':-5,'red':-2},
'supply':4},
'Hellhound':{'costDict':{'gold':-5,'blue':-1,'red':-1},
'supply':10},
'Infusion Grid':{'costDict':{'gold':-5,'blue':-1},
'supply':10},
'Iso Kronus':{'costDict':{'gold':-5,'green':-1},
'supply':10},
'Kinetic Driver':{'costDict':{'gold':-5,'green':-1},
'supply':4},
'Rhino':{'costDict':{'gold':-5,'red':-1},
'supply':10},
'Shiver Yeti':{'costDict':{'gold':-5,'red':-1},
'supply':10},
'Shredder':{'costDict':{'gold':-5,'blue':-1},
'supply':10},
'Thorium Dynamo':{'costDict':{'gold':-5,'energy':-1},
'supply':4},
'Tyranno Smorcus':{'costDict':{'gold':-5,'red':-2},
'supply':4},
'Urban Sentry':{'costDict':{'gold':-5,'green':-1,'blue':-1},
'supply':10},
'Wall':{'costDict':{'gold':-5,'blue':-1},
'supply':10},
'Wild Drone':{'costDict':{'gold':-5,'energy':-2},
'supply':4},
'Xeno Guardian':{'costDict':{'gold':-5,'green':-1,'blue':-2},
'supply':10},
'Zemora Voidbringer':{'costDict':{'gold':-5,'green':-3},
'supply':1},
'Aegis':{'costDict':{'gold':-6,'green':-3},
'supply':10},
'Animus':{'costDict':{'gold':-6},
'supply':10},
'Borehole Patroller':{'costDict':{'gold':-6,'green':-1,'blue':-1},
'supply':10},
'Corpus':{'costDict':{'gold':-6,'red':-2},
'supply':4},
'Ebb Turbine':{'costDict':{'gold':-6,'energy':-1,'blue':-1},
'supply':10},
'Gauss Cannon':{'costDict':{'gold':-6,'green':-1},
'supply':10},
'Lancetooth':{'costDict':{'gold':-6,'blue':-1},
'supply':10},
'Militia':{'costDict':{'gold':-6,'blue':-1},
'supply':10},
'Savior':{'costDict':{'gold':-6},
'supply':1},
'Steelsplitter':{'costDict':{'gold':-6,'blue':-1},
'supply':10},
'Synthesizer':{'costDict':{'gold':-6,'blue':-1},
'supply':4},
'Arka Sodara':{'costDict':{'gold':-7,'blue':-2,'red':-1},
'supply':1},
'Bloodrager':{'costDict':{'gold':-7,'red':-1},
'supply':10},
'Doomed Wall':{'costDict':{'gold':-7,'blue':-1},
'supply':10},
'Iceblade Golem':{'costDict':{'gold':-7,'blue':-1,'red':-1},
'supply':10},
'Protoplasm':{'costDict':{'gold':-7,'green':-2,'red':-2},
'supply':10},
'Sentinel':{'costDict':{'gold':-7,'green':-1,'red':-1},
'supply':10},
'Tantalum Ray':{'costDict':{'gold':-7,'green':-2},
'supply':10},
'Tia Thurnax':{'costDict':{'gold':-7,'green':-3,'red':-1},
'supply':1},
'A. R. Groans':{'costDict':{'gold':-8,'green':-1,'blue':-1,'red':-2},
'supply':1},
'Arms Race':{'costDict':{'gold':-8,'green':-1,'blue':-1,'red':-1},
'supply':4},
'Blood Phage':{'costDict':{'gold':-8,'energy':-1,'red':-1},
'supply':4},
'Chieftain':{'costDict':{'gold':-8,'green':-2,'blue':-1},
'supply':10},
'Energy Matrix':{'costDict':{'gold':-8,'blue':-2},
'supply':4},
'Gaussite Symbiote':{'costDict':{'gold':-8,'red':-2},
'supply':4},
'Glaciator':{'costDict':{'gold':-8},
'supply':1},
'Shadowfang':{'costDict':{'gold':-8,'red':-3},
'supply':10},
'Doomed Mech':{'costDict':{'gold':-9,'blue':-2},
'supply':10},
'The Wincer':{'costDict':{'gold':-9,'green':-1,'blue':-2,'red':-1},
'supply':1},
'Grenade Mech':{'costDict':{'gold':-10,'blue':-2},
'supply':4},
'Hannibull':{'costDict':{'gold':-10,'blue':-1,'red':-1},
'supply':4},
'Polywall':{'costDict':{'gold':-10,'blue':-1},
'supply':10},
'Redeemer':{'costDict':{'gold':-10,'green':-1,'blue':-1},
'supply':4},
'Cauterizer':{'costDict':{'gold':-11,'blue':-1,'red':-2},
'supply':4},
'Mahar Rectifier':{'costDict':{'gold':-11,'green':-2},
'supply':10},
'Tesla Coil':{'costDict':{'gold':-11,'green':-2,'blue':-1},
'supply':4},
'Xaetron':{'costDict':{'gold':-11,'green':-5},
'supply':1},
'Aurb Magnifier':{'costDict':{'gold':-12},
'supply':1},
'Cynestra':{'costDict':{'gold':-12,'green':-3,'red':-1},
'supply':4},
'Drake':{'costDict':{'gold':-12,'blue':-2},
'supply':4},
'Gauss Fabricator':{'costDict':{'gold':-12,'green':-4},
'supply':1},
'Plasmafier':{'costDict':{'gold':-12,'green':-3,'blue':-1},
'supply':4},
'Tatsu Nullifier':{'costDict':{'gold':-12,'red':-4},
'supply':4},
'Valkyrion':{'costDict':{'gold':-12,'green':-2,'blue':-1,'red':-1},
'supply':4},
'Amporilla':{'costDict':{'gold':-13,'red':-3},
'supply':4},
'Apollo':{'costDict':{'gold':-13,'blue':-3},
'supply':1},
'Vai Mauronax':{'costDict':{'gold':-13,'blue':-1,'red':-4},
'supply':1},
'Colossus':{'costDict':{'gold':-15,'green':-1,'blue':-2,'red':-2},
'supply':4},
'Omega Splitter':{'costDict':{'gold':-15,'blue':-3},
'supply':4},
'Thunderhead':{'costDict':{'gold':-15,'green':-5,'blue':-1},
'supply':1},
'Asteri Cannon':{'costDict':{'gold':-16,'green':-4},
'supply':4},
'Defense Grid':{'costDict':{'gold':-16,'blue':-3},
'supply':1},
'Lucina Spinos':{'costDict':{'gold':-17,'red':-4},
'supply':1},
'Centurion':{'costDict':{'gold':-18,'green':-2,'blue':-2,'red':-1},
'supply':1},
'Deep Impact':{'costDict':{'gold':-20},
'supply':1},
'Odin':{'costDict':{'gold':-20,'blue':-3},
'supply':1},
'Immaculon':{'costDict':{'gold':-25,'energy':-5},
'supply':1},
'EMP':{'costDict':{'gold':-40},
'supply':1},
}